spring:
    application:
        name: auth-service
    mail:
        host: smtp.gmail.com
        port: 587
        username: amirudhshanmukha2399@gmail.com
        password: incg fxmb epll aizw
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    kafka:
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
server:
    port: 4005