### PUT request to update Patient
PUT http://localhost:8080/api/v1/patient/13e256ac-bf34-4644-bf88-97a1c3ec9cc2
Content-Type: application/json

{
  "name": "anirudh",
  "email": "amirudhshanmukha2399@gmail.com",
  "address": "32,panchajanyam,Bangalore",
  "dateOfBirth": "1999-11-23"
}
###