logging:
    level:
        root: info
spring:
    application:
        name: patient-service
        #uncomment to enable props for local testing using mysql
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        password: Optimus@2399
#        url: jdbc:mysql://localhost:3306/pms
#        username: root
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL8Dialect
#        hibernate:
#            ddl-auto: none
#        properties:
#            hibernate:
#                format_sql: true
#        show-sql: true
#    sql:
#        init:
#            mode: always
server:
    port: 4000
